### ISSUE TITLE
Error when using video 

### ISSUE THREAD

**Issue by saeedkhanehgir** [PaddlePaddle/FastDeploy#516]
Hi
Thanks for sharing this project. 
I want to use yolov5-face detection in **c++ on raspberry pi**. 
when I use it for **image**, everything is ok. but when I use it for **video**, I get the below error. 

```
[INFO] fastdeploy/runtime.cc(481)::Init	Runtime initialized with Backend::ORT in Device::CPU.
Error opening video stream or file
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.14) /jiangjiajun/opencv-3.4.14/modules/highgui/src/window.cpp:652: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

Aborted (core dumped)
```
I am working on raspberry pi with **ubuntu 22.04 64bit** and my Opencv version is **4.3.0** and  Opencv is built from source.
I built Opencv by [link](https://qengineering.eu/install-opencv-4.3-on-raspberry-64-os.html).  
I upgraded Opencv version to **4.5.5** but I got the above error, again.

**Comment by jiangjiajun** [comment]
Hi, @saeedkhanehgir 

Did you built fastdeploy by yourself, or you  download the prebuilt FastDeploy?

**Comment by saeedkhanehgir** [comment]
Hi @jiangjiajun
I built by myself.

**Comment by jiangjiajun** [comment]
I think you are using the prebuilt OpenCV(version 3.4.14, without video enabled) which is integrated in FastDeploy by default. Could you rebuild FastDeploy using `-DOPENCV_DIRECTORY`(if python, `export OPENCV_DIRECTORY`), to build FastDeploy with your own OpenCV

**Comment by saeedkhanehgir** [comment]
@jiangjiajun 
Thanks for your answer. when I built OpenCV I set   **-D CMAKE_INSTALL_PREFIX=/usr/local** . Now I should set **-DOPENCV_DIRECTORY=/usr/local/ ?**

**Comment by saeedkhanehgir** [comment]
@jiangjiajun 
Thanks, it works.

**Comment by liuyingtao941212** [comment]
> I think you are using the prebuilt OpenCV(version 3.4.14, without video enabled) which is integrated in FastDeploy by default. Could you rebuild FastDeploy using `-DOPENCV_DIRECTORY`(if python, `export OPENCV_DIRECTORY`), to build FastDeploy with your own OpenCV

如果我是用的预编译的包 这个问题应该怎么解决呢？
